### ISSUE TITLE
AttributeError: module 'transformers.generation.utils' has no attribute '__module__'

### ISSUE THREAD

**Issue by yfangZhang** [nju-websoft/KnowLA#6]
python test_truthfulqa.py --is_KG=True 

Traceback (most recent call last):
  File "/root/zhangyf/KnowLA/test_truthfulqa.py", line 206, in <module>
    fire.Fire(main)
  File "/opt/anaconda3/envs/llm_envs/lib/python3.9/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/anaconda3/envs/llm_envs/lib/python3.9/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/anaconda3/envs/llm_envs/lib/python3.9/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/zhangyf/KnowLA/test_truthfulqa.py", line 53, in main
    shutil.copyfile(base_model + "/utils.py", os.path.abspath(sys.modules[utils.__module__].__file__), follow_symlinks=True)
AttributeError: module 'transformers.generation.utils' has no attribute '__module__'

**Comment by luoxindi** [comment]
This problem is caused by different transformers package versions, I'll fix it as soon as possible!
